name: CI/CD Test
on:
  push:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Say the thing...
        run: echo "Hello World!"

  run-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
    
  run-tests:
    runs-on: ubuntu-latest
    needs: run-checks
    steps:  
      - name: Checkout Repo
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

  
  deploy:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:

      - name: Checkout Repo    
        uses: actions/checkout@v4

      - name: setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
      - name: setup RDS CLI
        with:
          db-port: ${{ secrets.DB_PORT}}
          db-username: ${{ secrets.DB_USERNAME}}
          db-password: ${{ secrets.DB_PASSWORD}}
      

     




